In [2]:
import numpy as np

In [3]:
arr1 = np.array([45,52,36,30])
arr1

array([45, 52, 36, 30])

In [3]:
arr1.shape

(4,)

In [4]:
arr1.ndim

1

In [5]:
arr1.dtype

dtype('int32')

In [5]:
arr2 = np.array([[45,23,69,36],[14,20,30,60],[89,56,60,66]])
arr12 = np.array([[45,23,69,36],[14,20,30,60],[89,56,60,66]])
arr123 = arr2 * arr12 
arr123

array([[2025,  529, 4761, 1296],
       [ 196,  400,  900, 3600],
       [7921, 3136, 3600, 4356]])

In [6]:
arr2.shape

(3, 4)

In [7]:
arr2.ndim

2

In [10]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
np.ones((3,3)) * 5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [15]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [11]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [17]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [18]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [20]:
arr3 = np.arange(1,101)
arr3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [13]:
arr3 = np.arange(1,101,2)
arr3

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [22]:

arr4 = np.random.randint(14,90,120)
arr4

array([24, 34, 36, 58, 36, 43, 50, 47, 57, 57, 33, 39, 53, 20, 50, 23, 31,
       48, 72, 65, 51, 48, 68, 61, 19, 20, 49, 20, 88, 59, 57, 30, 73, 29,
       32, 88, 84, 48, 64, 54, 35, 39, 34, 56, 58, 78, 67, 69, 65, 86, 39,
       44, 77, 78, 87, 62, 32, 40, 61, 22, 52, 28, 67, 65, 47, 51, 31, 89,
       81, 18, 77, 61, 88, 16, 74, 61, 43, 87, 84, 88, 49, 51, 17, 60, 80,
       14, 47, 57, 38, 52, 18, 69, 55, 47, 47, 19, 70, 46, 32, 70, 17, 66,
       22, 34, 45, 55, 80, 38, 76, 89, 50, 39, 22, 49, 37, 81, 47, 53, 19,
       76])

In [18]:
np.random.seed(5)
arr4 = np.random.randint(14,90,120)
arr4

array([75, 30, 87, 22, 76, 41, 44, 21, 29, 67, 41, 58, 89, 79, 61, 44, 32,
       23, 55, 76, 15, 30, 19, 72, 14, 18, 50, 65, 41, 45, 16, 82, 52, 33,
       32, 21, 44, 76, 25, 81, 79, 69, 17, 41, 43, 47, 21, 30, 28, 45, 23,
       52, 61, 30, 19, 48, 59, 73, 38, 27, 45, 46, 58, 19, 28, 61, 14, 21,
       30, 78, 22, 58, 51, 89, 19, 36, 66, 83, 74, 43, 84, 49, 34, 63, 86,
       46, 27, 32, 66, 36, 72, 63, 18, 50, 55, 34, 46, 24, 45, 29, 36, 84,
       23, 77, 28, 80, 71, 33, 78, 22, 22, 85, 26, 34, 73, 86, 88, 86, 46,
       29])

In [33]:
arr5 = arr4.reshape(10,12)
arr5

array([[75, 30, 87, 22, 76, 41, 44, 21, 29, 67, 41, 58],
       [89, 79, 61, 44, 32, 23, 55, 76, 15, 30, 19, 72],
       [14, 18, 50, 65, 41, 45, 16, 82, 52, 33, 32, 21],
       [44, 76, 25, 81, 79, 69, 17, 41, 43, 47, 21, 30],
       [28, 45, 23, 52, 61, 30, 19, 48, 59, 73, 38, 27],
       [45, 46, 58, 19, 28, 61, 14, 21, 30, 78, 22, 58],
       [51, 89, 19, 36, 66, 83, 74, 43, 84, 49, 34, 63],
       [86, 46, 27, 32, 66, 36, 72, 63, 18, 50, 55, 34],
       [46, 24, 45, 29, 36, 84, 23, 77, 28, 80, 71, 33],
       [78, 22, 22, 85, 26, 34, 73, 86, 88, 86, 46, 29]])

In [34]:
arr5 = arr4.reshape(10,12)
arr5

array([[75, 30, 87, 22, 76, 41, 44, 21, 29, 67, 41, 58],
       [89, 79, 61, 44, 32, 23, 55, 76, 15, 30, 19, 72],
       [14, 18, 50, 65, 41, 45, 16, 82, 52, 33, 32, 21],
       [44, 76, 25, 81, 79, 69, 17, 41, 43, 47, 21, 30],
       [28, 45, 23, 52, 61, 30, 19, 48, 59, 73, 38, 27],
       [45, 46, 58, 19, 28, 61, 14, 21, 30, 78, 22, 58],
       [51, 89, 19, 36, 66, 83, 74, 43, 84, 49, 34, 63],
       [86, 46, 27, 32, 66, 36, 72, 63, 18, 50, 55, 34],
       [46, 24, 45, 29, 36, 84, 23, 77, 28, 80, 71, 33],
       [78, 22, 22, 85, 26, 34, 73, 86, 88, 86, 46, 29]])

In [35]:
arr5[4,6]

19

In [37]:
arr5[3:7,5:8]


array([[69, 17, 41],
       [30, 19, 48],
       [61, 14, 21],
       [83, 74, 43]])

In [62]:
arr5[3:7,5:8] = 85
arr5

array([[75, 30, 87, 22, 76, 41, 44, 21, 29, 67, 41, 58],
       [89, 79, 61, 44, 32, 23, 55, 76, 15, 30, 19, 72],
       [14, 18, 50, 65, 41, 45, 16, 82, 52, 33, 32, 21],
       [44, 76, 25, 81, 79, 85, 85, 85, 43, 47, 21, 30],
       [28, 45, 23, 52, 61, 85, 85, 85, 59, 73, 38, 27],
       [45, 46, 58, 19, 28, 85, 85, 85, 30, 78, 22, 58],
       [51, 89, 19, 36, 66, 85, 85, 85, 84, 49, 34, 63],
       [86, 46, 27, 32, 66, 36, 72, 63, 18, 50, 55, 34],
       [46, 24, 45, 29, 36, 84, 23, 77, 28, 80, 71, 33],
       [78, 22, 22, 85, 26, 34, 73, 86, 88, 86, 46, 29]])

In [41]:
arr6 = arr5.flatten()
arr6

array([75, 30, 87, 22, 76, 41, 44, 21, 29, 67, 41, 58, 89, 79, 61, 44, 32,
       23, 55, 76, 15, 30, 19, 72, 14, 18, 50, 65, 41, 45, 16, 82, 52, 33,
       32, 21, 44, 76, 25, 81, 79, 85, 85, 85, 43, 47, 21, 30, 28, 45, 23,
       52, 61, 85, 85, 85, 59, 73, 38, 27, 45, 46, 58, 19, 28, 85, 85, 85,
       30, 78, 22, 58, 51, 89, 19, 36, 66, 85, 85, 85, 84, 49, 34, 63, 86,
       46, 27, 32, 66, 36, 72, 63, 18, 50, 55, 34, 46, 24, 45, 29, 36, 84,
       23, 77, 28, 80, 71, 33, 78, 22, 22, 85, 26, 34, 73, 86, 88, 86, 46,
       29])

In [42]:
np.sum(arr6)

6238

In [43]:
np.mean(arr6)

51.983333333333334

In [44]:
np.median(arr6)

46.5

In [45]:
np.max(arr6)

89

In [46]:
np.min(arr6)

14

In [47]:
np.sqrt(arr6)

array([8.66025404, 5.47722558, 9.32737905, 4.69041576, 8.71779789,
       6.40312424, 6.63324958, 4.58257569, 5.38516481, 8.18535277,
       6.40312424, 7.61577311, 9.43398113, 8.88819442, 7.81024968,
       6.63324958, 5.65685425, 4.79583152, 7.41619849, 8.71779789,
       3.87298335, 5.47722558, 4.35889894, 8.48528137, 3.74165739,
       4.24264069, 7.07106781, 8.06225775, 6.40312424, 6.70820393,
       4.        , 9.05538514, 7.21110255, 5.74456265, 5.65685425,
       4.58257569, 6.63324958, 8.71779789, 5.        , 9.        ,
       8.88819442, 9.21954446, 9.21954446, 9.21954446, 6.55743852,
       6.8556546 , 4.58257569, 5.47722558, 5.29150262, 6.70820393,
       4.79583152, 7.21110255, 7.81024968, 9.21954446, 9.21954446,
       9.21954446, 7.68114575, 8.54400375, 6.164414  , 5.19615242,
       6.70820393, 6.78232998, 7.61577311, 4.35889894, 5.29150262,
       9.21954446, 9.21954446, 9.21954446, 5.47722558, 8.83176087,
       4.69041576, 7.61577311, 7.14142843, 9.43398113, 4.35889

In [48]:
np.var(arr6)

573.4830555555556

In [49]:
np.std(arr6)

23.947506249201723

In [50]:
np.percentile(arr6,45)

45.0

In [54]:
##Excercise
## generate a random number btw 55 and 166 total of 150 using 2 as the seed number 
## reshape to 2d to the nearest rows and columns
## find the mean,sum,median,25th percentile,65 percentile

np.random.seed(2)
arr7 = np.random.randint(55,167,150)
arr7

array([ 95,  70, 164, 127,  77,  98, 137, 130, 159,  62,  89, 104, 150,
       130, 140, 102, 118,  86, 145,  75,  92,  94, 122, 157,  59,  97,
       162, 106, 158,  93, 161,  88, 113, 122, 124, 143, 123, 101, 125,
       150, 138,  86, 121, 135, 107, 165, 131, 105,  59, 145, 118, 134,
       104,  94, 101,  63, 105, 164,  70, 160, 164,  63,  72,  77, 128,
       112, 160, 165, 145, 117, 138, 151,  98,  87,  81,  63, 131,  65,
        95,  89, 115,  64, 156, 125, 141, 125,  74, 111, 137,  56, 123,
        95, 136, 116, 125, 156, 152,  73, 139, 145, 142,  77,  98, 107,
       156, 129, 127, 145, 154, 146, 151,  71, 110,  76,  98, 148, 135,
        95, 125, 129,  92, 114,  72,  70,  85, 132,  81,  94, 162, 118,
       166,  75,  77, 114, 104, 155,  82,  55, 117,  95, 113, 147,  91,
       118, 130, 165, 105, 128,  62, 104])

In [55]:
arr8 = arr7.reshape(10,15)
arr8


array([[ 95,  70, 164, 127,  77,  98, 137, 130, 159,  62,  89, 104, 150,
        130, 140],
       [102, 118,  86, 145,  75,  92,  94, 122, 157,  59,  97, 162, 106,
        158,  93],
       [161,  88, 113, 122, 124, 143, 123, 101, 125, 150, 138,  86, 121,
        135, 107],
       [165, 131, 105,  59, 145, 118, 134, 104,  94, 101,  63, 105, 164,
         70, 160],
       [164,  63,  72,  77, 128, 112, 160, 165, 145, 117, 138, 151,  98,
         87,  81],
       [ 63, 131,  65,  95,  89, 115,  64, 156, 125, 141, 125,  74, 111,
        137,  56],
       [123,  95, 136, 116, 125, 156, 152,  73, 139, 145, 142,  77,  98,
        107, 156],
       [129, 127, 145, 154, 146, 151,  71, 110,  76,  98, 148, 135,  95,
        125, 129],
       [ 92, 114,  72,  70,  85, 132,  81,  94, 162, 118, 166,  75,  77,
        114, 104],
       [155,  82,  55, 117,  95, 113, 147,  91, 118, 130, 165, 105, 128,
         62, 104]])

In [56]:
np.mean(arr8)

114.4

In [57]:
np.sum(arr8)

17160

In [58]:
np.median(arr8)

116.5

In [59]:
np.percentile(arr8,25)

92.0

In [60]:
np.percentile(arr8,65)

129.0